### ISSUE TITLE
Servo Controlls via Firmware occur in Hardware Trouble

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#862] opened 2022-06-27 13:24 UTC
**Is your feature request related to a problem? Please describe.**
Looks like Firmware settings for Servo are critical for some ( a lot) of Servo Brands.   The Lower Flank is wrong and occure in a overheat or kill of Hardware

**Describe the solution you'd like**
Check / Rethink of used parameters

**Describe alternatives you've considered**
If needed a Optional Methode for effected users to avoid the problem

**Additional context**
Initial Request on Forum :  [https://www.mobiflight.com/forum/message/26171.html](url)

**Comment by DocMoebiuz** [comment] 2022-07-03 12:20
@pizman - This is reported as a feature request. What is the requested feature? Or is this a bug report? Then please provide steps to reproduce the problem. Thanks.

**Comment by DocMoebiuz** [comment] 2022-07-03 12:22
As a workaround for the guy from the forum post: He can simply add a value to increase the 0 to e.g. 10. Then the servo might not have an issue.

**Comment by tigert** [comment] 2022-12-29 19:47
Maybe initialize servos at 1500ms pulse width (center) until you send a real value, that should be safe for any servo?

**Comment by DocMoebiuz** [comment] 2023-10-21 19:33
I will close this because we haven't had this issues often enough.

**Closed by DocMoebiuz** 2023-10-21 19:33 UTC
Labels: enhancement, firmware
