### ISSUE TITLE
Mobiflight connector interfering with CPFlight MCP737 EL initialization in X-Plane 11

### ISSUE THREAD

**Issue by teropart** [MobiFlight/MobiFlight-Connector#672] opened 2022-01-24 11:58 UTC
See discord description as well: https://discord.com/channels/608690978081210392/608690978735390752/934846445037682718

In short, MF connector is reserving COM port assigned to CPflight MCP737 EL. And if MF is opened (not even Run, just opened) before X-Plane 11 has loaded the aircraft, the MCP will not get initialized and is not usable in the sim. One has to reboot the PC to clear the COM reservation. Or use a tool like COM name arbiter to use "unreserve" function to clear the COM port reservation.

Workaround is to start the X-Plane 11 first, load the airplane, let the MCP737 initialize (init happens during plane loading, not when XP11 loads to Menu screen), and only after MCP is initialized (as shown by brief flashing of digits on MCP screens) the Mobiflight connector can be opened and used.

Likely root-cause is that while MF connector scans Arduinos connected to the PC, the MCP737 Arduino (even when it does not have MF FW installed) gets scanned and the associated COM port is never released after the scan. Hence the Init on plane loading is not succesful. X-Plane LOG shows that device in the associated COM port is not responding (CPflight SW printouts).

MB version 9.2.0
FW for connected MF Arduinos 2.0.0

**Comment by pizman** [comment] 2022-01-25 14:26
#551

**Comment by DocMoebiuz** [comment] 2022-06-06 11:41
I can confirm that MobiFlight does not keep the connection open to a COM Port where it could not find a Mobiflight board.
This seems to be a timing issue and the feature of #551 will provide the means to solve it properly.

I will close this issue.

**Closed by DocMoebiuz** 2022-06-06 11:41 UTC
Labels: enhancement, UI
