### ISSUE TITLE
Test input action via UI (similar to output configuration)

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#334] opened 2021-06-18 20:43 UTC
On the input config wizard, after selecting and configuring an Input Action, e.g. MSFS2020 Event, I can trigger this event via the UI and check if it works correctly in the simulator. 

This is helpful for troubleshooting input configs without having to have a working switch.

New idea:
During my last video it became obvious to me that the Test Methods would totally make sense in the MobiFlight Device Settings. Having them there, after uploading a new configuration would be helpful.

[Issue created by DocMoebiuz: 2021-04-12]

**Comment by DocMoebiuz** [comment] 2023-02-04 08:14
duplicate of #297

**Closed** 2023-02-04 08:15 UTC
Labels: enhancement, UI
