### ISSUE TITLE
Config Wizard page for Display tab, X-Plane action, hides the value expression, preventing entry

### ISSUE THREAD

**Issue by quizkid** [MobiFlight/MobiFlight-Connector#1067] opened 2023-01-14 22:51 UTC
This is a GUI issue which prevents entry of the expression value for X-Plane presets. A hack workaround is to type a value into the generated MCC file, then load it. This works, but is quite annoying.

Steps to reproduce
1. Create any Output Config
2. Click ... to open Config Wizard
3. Open the Display tab
4. Under Display Type, select Input Action and OnChange
5. Under On Change, select Action Type of X-Plane (all versions)
6. Select any preset
7. Check the box "Show Preset Code"
8. The expected value field with corresponding "hint" that reads "supports input value ...." is not visible, so no value can be entered.

I noticed that the graphic lines stop, so I think the fix is a matter of enlarging the graphical window so that the field is viewable/editable.

![MobiFlightExpressionFieldMissing](https://user-images.githubusercontent.com/4828541/212500532-5c0f2db8-fc7b-41c4-9f25-e3bf6a92e1a2.png)

**Comment by DocMoebiuz** [comment] 2023-01-15 09:57
Thanks for reporting, this is a duplicate of #1050 which is already fixed

**Closed by DocMoebiuz** 2023-01-15 09:57 UTC
