### ISSUE TITLE
Crash in Mobiflight when connecting to xplane

### ISSUE THREAD

**Issue by neilenns** [MobiFlight/MobiFlight-Connector#1440] opened 2023-11-22 03:04 UTC
Reported by two users in Discord. To reproduce:

1. Run xplane12
2. Run mobiflight

Result: Crash

Apparently running Mobiflight before xplane does not have the issue. Here are two call stacks from the same user.

Config file not linked to an aircraft:

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/9524118/616a8a21-c6cf-425e-827a-dcad784adaea)

Config file linked to an aircraft:

![image](https://github.com/MobiFlight/MobiFlight-Connector/assets/9524118/6f9ac621-4288-470d-a643-57b28164d94d)

**Comment by neilenns** [comment] 2023-11-22 03:12
I looked into those xplane crash callstacks a bit. both of the crashes are in code we don't own. My best guess is for some reason the connection to xplane isn't working.

The call stacks are different for the "not linked" vs. "linked" config.

We don't have any exception handling around the calls. In CheckForAircraftName() it's the call to Start() that crashes, and there's no try/catch. In Stop() it's the call to Stop() that crashes.

We can easily put try/catch blocks around those two places and not crash, but I have no idea why the xplane library would be having an issue in either case.

**Comment by DocMoebiuz** [comment] 2023-11-22 05:47
I tried both, either run xplane first and then MobiFlight or the other way around. 

I was not able to reproduce the error. Both times switching planes and loading linked profiles worked.

**Comment by DocMoebiuz** [comment] 2023-11-26 20:04
@neilenns please provide discord links so that we can check whether there was ever a follow up to this. If we cannot reproduce the issue, and if there is no one providing more information on it, then we don't need to keep this issue open.

**Comment by DocMoebiuz** [comment] 2023-11-26 20:17
I looked into the code again, it looks like this happens in the XplaneConnector in line https://github.com/MaxFerretti/XPlaneConnector/blob/80242ab3a5323ddc85f2a019b9a07d29efd5e8ff/XPlaneConnector/XPlaneConnector/XPlaneConnector.cs#L67

for some reason the IP Address of xplane is null... i wonder if that is some kind of Anti Virus issue.

**Comment by neilenns** [comment] 2023-11-27 12:32
> @neilenns please provide discord links so that we can check whether there was ever a follow up to this. If we cannot reproduce the issue, and if there is no one providing more information on it, then we don't need to keep this issue open.

Here you go: https://discord.com/channels/608690978081210392/1176229213058121769

**Comment by DocMoebiuz** [comment] 2023-12-17 11:26
There was no follow up on this. I will close this.

**Closed by DocMoebiuz** 2023-12-17 11:26 UTC
Labels: cant reproduce
