### ISSUE TITLE
When remapping a config to an identical board with different serial number, encoders are not mapped

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#610] opened 2021-12-11 00:59 UTC
When you replace an arduino with one that has the same pin definitions but different serial number (like if you make several identical panels for a group of people, or if you regenerate the serial, or replace a broken arduino etc) "Manage orphaned serials" does map most of your pins correctly, but for some reason encoders are not being mapped. The Arduino is mapped for each encoder, but the encoder devices themselves are not selected. even of the names and pin numbers are identical.

**Comment by neilenns** [comment] 2021-12-13 17:44
@tigert What version of MobiFlight was this in?

**Comment by tigert** [comment] 2021-12-28 20:49
This was in whatever was the latest at the time I wrote the issue. Maybe 9.1? I need to see if I can reproduce it still.

**Comment by DocMoebiuz** [comment] 2022-04-21 19:00
I cannot reproduce this behavior anymore (9.3.2).
I will close this.

**Closed by DocMoebiuz** 2022-04-21 19:00 UTC
Labels: bug
