### ISSUE TITLE
Update 9.6.0.4 not working

### ISSUE THREAD

**Issue by MStallen** [MobiFlight/MobiFlight-Connector#1080] opened 2023-01-20 10:31 UTC
After updating to 9.6.0.4 MFConnector on start-up shows an unhandled exception. "device is not ready". If I choose to continue MFConnector get stuck in "checking for Firmware Updates"

steps:
- Update to 9.6.0.4
- Start MFConnector

 - MobiFlight Version: 9.6.0.4
 - Firmware Arduino Mega 2650 : 2.3.0
 - FlightSim: MSFS2020

Reinstalling 9.6.0.0 clears the error. But choosing update to 9.6.0.4 again introduces the error

**Comment by DocMoebiuz** [comment] 2023-01-20 10:54
Thanks for reporting this. You probably have a DVD drive and this was something overseen in the new Pico support. 

Please confirm and then we can close this as duplicate of #1074

**Comment by MStallen** [comment] 2023-01-20 11:54
I can confirm my DVD drive

**Comment by DocMoebiuz** [comment] 2023-01-20 19:31
duplicate of https://github.com/MobiFlight/MobiFlight-Connector/issues/1074

**Closed by DocMoebiuz** 2023-01-20 19:31 UTC
