### ISSUE TITLE
Custom MSFS2020 events could have a "test" button

### ISSUE THREAD

**Issue by tigert** [MobiFlight/MobiFlight-Connector#552] opened 2021-11-03 10:42 UTC
It would be good to have an easier way to test a custom msfs2020 event with a "Test in simulator" button in the editor window.

Right now you have to edit, click OK to close the dialog, test it, open it again if you need to edit, and close and then again test.

It could also fire the event "live" from the button it is tied to, but then you would also get the OnRelease event etc. Maybe just "test" buttons on all events (OnPress, OnRelease, encoder events) would be simplest? Some visual clutter but maybe more convenient editing?

Also, I dont know if Simconnect returns some error messages / status codes, could show them in the debug log if we dont already?

**Comment by MobiFlight-Admin** [comment] 2021-11-04 07:48
Hi @tigert - that's a great idea, this should be added  in general to all input actions - we already have an issue for that: #297

**Comment by neilenns** [comment] 2021-11-06 00:34
@MobiFlight-Admin Can we just close this issue as a duplicate then of #297?

**Comment by pizman** [comment] 2021-11-10 20:17
Déjà-vu  ....    Feels like i requested this some months ago.....   But there @DocMoebiuz means this is not usefull for "normal" users.  ;-)
Whatever..... I still vote for THIS !!

BUT   This also need a Rework of the Whole Input Logic......
If the TEST only exist in a Config where i HAVE TO select a Board and a Device ( so Mega must be connected) then i could also press the real button instead ..... Means no Benefit.

Cool would be a own Tab ( For Input Configs) where i have all Commands ( Press, Release, Left Right and so on) to Test a Input WITHOUT a Device selected......
BUT This is not possible in case we can not choose for a Input Item without select a Device prior.

Means the Inputs have to work like Outputs.... We select the "Function" on One Tab..... And we Select the Device "indipended" on a other Tab (optional)  ...... Then Config in theory work without a Device !   Just by this Testing Buttons!

**Comment by tigert** [comment] 2021-11-23 20:55
Or we just let the user choose event type without selecting a device yet? This would make it easier to share config files as examples too, currently it is really cumbersome to study someone elses config file unless you have the exactly same pin layout flashed on one of your own arduionos.

Would it also be possible to "detect event" and just flip a switch?

**Comment by DocMoebiuz** [comment] 2023-02-04 08:10
duplicate of #297

**Closed by DocMoebiuz** 2023-02-04 08:10 UTC
Labels: enhancement
