### ISSUE TITLE
Change red exclamation for "Precondition not met"

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#1003] opened 2022-11-10 21:25 UTC
**Is your feature request related to a problem? Please describe.**
The red exclamation mark is currently used for both errors found and precondition not met.  This tends to confuse new users trying to use preconditions and getting alarmed at seeing the red exclamation mark on their configs.

**Describe the solution you'd like**
Change the red exclamation mark color to yellow.

**Describe alternatives you've considered**
Change to a different icon with different color will also work.

**Additional context**
None

**Comment by DocMoebiuz** [comment] 2022-11-16 22:31
Linked with #333

**Comment by DocMoebiuz** [comment] 2022-11-16 22:32
Third is no simconnection

**Comment by DocMoebiuz** [comment] 2022-11-16 22:37
Closed as duplicate of #333

**Closed by DocMoebiuz** 2022-11-16 22:37 UTC
Labels: enhancement
