### ISSUE TITLE
Mobiflight not recognizing MSFS has started automatically in version 9.1

### ISSUE THREAD

**Issue by Fellstone7** [MobiFlight/MobiFlight-Connector#615] opened 2021-12-14 09:11 UTC
**Describe the bug**
Running windows 11 with WASM, FSUIPC 7 and SIM update 6 and now 7 Mobiflight does not recognise the flight sim is running. However a work around to kick start Mobiflight to recognize the sim is active is to go into settings and change randomly the FSUIPC rate either faster or slower and hit OK. Mobiflight then automatically finds the sim is working and runs correctly.

**Steps To Reproduce**
1. Open MSFS with the FSUIPC short cut
2. Open Mobiflight
3. Once MSFS has started Mobiflight still has not detected the sim.
4. Go to Settings in Mobiflight and change FSUIPC poll rate to any new value and hit ok. Now Mobiflight works ok.

**Expected behavior**
Previous version would automatically detect MSFS running and connected

**Actual behavior**
User needs to force Mobiflight to look to see if Sim is running

**Details**
 - MobiFlight Version: 9.1.0
 - FlightSim: MSFS 2020 both sim update 6 and now with sim update 7
 - AddOn: FSUIPC v7.2.13
 - Operating System: Windows 11

**Additional context**
This bug is not a big issue as Mobiflight works ok with the work around but the previous version (8) did automatically work

**Comment by Fellstone7** [comment] 2021-12-16 10:17
Now removed FSUIPC and I can confirm the issue is still there as is the work around

**Comment by MobiFlight-Admin** [comment] 2021-12-16 13:48
there are hundreds of people using it including me - there must be something special about your case.

why are you still using fsuipc for MSFS2020?

when you say the sim is not detected, what is what you see? In the status bar you can click on the sim status to see more details.

Also, it can take up to 10 seconds for Mobiflight to detect the sim and especially the sim connect connection can take longer. Because it's not active from the beginning but i think once the flight gets loaded.

**Comment by Fellstone7** [comment] 2021-12-16 23:49
Hi

I remove FSUIPC as it was not needed.  I will try waiting longer and see if it does connect. But just changing the FSUIPC rate in any direction causes Mobiflight to connect straight away.

 

Thanks will report back when I have experimented with it. 

 

Thanks for getting back to me.

 

Nigel

**Comment by MobiFlight-Admin** [comment] 2021-12-16 23:57
Hi @Fellstone7 , asking about FSUIPC was really out of curiosity, i simply wanted to understand your requirement for it. If you don't need, switch to SimConnect. It is so much more straightforward.

**Comment by Fellstone7** [comment] 2021-12-17 14:48
Hi Sebastian

 

I have hi removed FSUIPC (which was the MSFS version) off the PC. Mobiflight is still working as before. I am also using SPAD.next as well to control my Saitek panels if that could be a culpit? 

 

What is interesting is after I kick start mobiflight by changing the FSUIPC time sampling rate in the settings mobiflight recognises MSFS is working but I still get a warning about SIMCONNECT ? see screen grab below.

I have also included the log file when I start mobiflight and after I have then kick started it with the setting change. If that help to under stand whats happening. I have also reinstalled Mobiflight as well. That has made no difference.

**Comment by MobiFlight-Admin** [comment] 2021-12-29 20:12
@Fellstone7 can you please tell me if this problem persists in 9.2?

**Comment by Fellstone7** [comment] 2021-12-30 11:41
Its still the same. The wasm connection and the sim are only picked up when I change a setting or alter a setting so the ok button on settings cam be click. Its like this triggers a reset or a sim check. Mobiflight then connects and srinks into the background running icons in the toolbar.

**Comment by DocMoebiuz** [comment] 2022-03-07 18:30
@Fellstone7  please try latest beta or 9.3 release and let me know if it still is a problem

**Comment by Fellstone7** [comment] 2022-03-12 14:43
Hi Sebastian

 

I am still having to manually kick MF to connect  to MSFS via a setting change.

 

N

**Comment by DocMoebiuz** [comment] 2022-04-02 20:01
@Fellstone7 is this resolved in 9.3? The WASM connection method was changed and hopefully it is working for you now.

**Comment by Fellstone7** [comment] 2022-04-09 08:22
Hi Sebastian

 

I still have to go into settings and change any parameter and change back then press ok to kick start Mobiflight. It works perfectly after that.

 

Thanks for keeping though on this minor issue.

 

Regards

 

Nigel

**Comment by DocMoebiuz** [comment] 2022-05-07 08:10
I can't reproduce it and it is nothing that other users are reporting. We can still have a screen share session some time but I will close this for now.

**Closed by DocMoebiuz** 2022-05-07 08:10 UTC
