### ISSUE TITLE
MF no longer starts by click a mcc file  ( via Open/Run with)

### ISSUE THREAD

**Issue by pizman** [MobiFlight/MobiFlight-Connector#750] opened 2022-04-02 14:47 UTC
**Describe the bug**
A user report in the past ( 9.0 and prior i think) he was be able to click on a MCC File ( e.g. as Desktop symbol or in File explorer)
and then MF Connector starts with that file.
I can not confirm this in case i never do it. I always "open" a file within MF Connectors LOAD Button.

**Steps To Reproduce**
Doubleclick on a MCC File 
(For sure the Filetyp *.mcc must have as prior Programm to Run selected Mobiflight....  Else use the "open With" Dialog and select MF)

**Expected behavior**
If user report correctly in older MF Versions THIS work and MF Startup ( i expect exactly with THAT File)
 
**Actual behavior**
MF for me not start.... The Windows Admin Mode request comes up (i use MF in Admin Mode) BUT it not opens behind or show something.... It also not run "hidden".
Feels like MF Startup crash!

**Additional context**
I wondering if this really was possible in the past!   Why do we use /CFG Code as exe parameters to run with a specific  File if we also could simply doubleclick on a mcc already !
Please Check this behaviour !

**Comment by DocMoebiuz** [comment] 2022-04-02 20:22
This thas never worked before. It is kind of a duplicate of #455, although there Trevor is talking about a mfmc file.

**Closed by DocMoebiuz** 2022-04-02 20:22 UTC
Labels: duplicate
