### ISSUE TITLE
MobiFlight reports an error flashing nano firmware, even if it eventually worked.

### ISSUE THREAD

**Issue by simontrhodes** [MobiFlight/MobiFlight-Connector#1216] opened 2023-05-14 12:48 UTC
**Describe the bug**
When flashing the firmware onto a Nano with an old bootloader, MobiFlight reports an error, even if it eventually worked.

**Steps To Reproduce**
1. Within MobiFlight Modules
2. Select an Arduino Nano
3. Click Update Firmware

**Expected behavior**
The firmware flashing is attempted at the high baud rate and fails without notifying the user.
The flashing is attempted again automatically at the lower baud rate and works.
An error is only shown if all attempts fail.

**Actual behavior**
An error is displayed from the first time the flash was executed,
even if the second attempt was successful.

**Details**
 - MobiFlight Version: Beta 9.7.1.1
 - FlightSim: None
 - AddOn: None

**Additional context**
Source code:
https://github.com/MobiFlight/MobiFlight-Connector/blob/main/MobiFlight/MobiFlightFirmwareUpdater.cs
Error handling starts at line 143.

**Comment by neilenns** [comment] 2023-05-14 16:51
I'm not able to reproduce this locally with the current code. @simontrhodes can you try with a timeout of 20000 in the arduino_nano.board.json file? I'm wondering if that's a difference between our setups.

**Comment by DocMoebiuz** [comment] 2023-10-31 21:21
@simontrhodes please provide the feedback on @neilenns recommended setting. Would be interesting to know if it helps

**Comment by DocMoebiuz** [comment] 2023-11-08 11:08
I bought a nano to be able to recreate this issue. I am not able with the one I have.

@simontrhodes is your nano one of those that uses an old bootloader?

**Comment by simontrhodes** [comment] 2023-11-08 13:51
Sorry @DocMoebiuz mine does have the old bootloader.
I can still replicate the bug with my Nano and the latest build.

When the log level is set to **debug**.
`11/08/2023 13:39:30(492): MobiFlightFirmwareUpdater.RunAvrDude(): C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\Arduino\hardware\tools\avr\bin\avrdude -C"C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\Arduino\hardware\tools\avr\etc\avrdude.conf" -x attempts=1 -patmega328p -carduino -PCOM5 -b115200 -D -Uflash:w:"C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\firmware\mobiflight_nano_2_4_2.hex":i
11/08/2023 13:39:30(789): <>c.<RunAvrDude>b__15_1(): avrdude: Setting number of retry attempts to 1
11/08/2023 13:39:33(834): <>c.<RunAvrDude>b__15_1(): avrdude: stk500_getsync() attempt 1 of 1: not in sync: resp=0x32
11/08/2023 13:39:34(353): <>c.<RunAvrDude>b__15_1(): avrdude: opening programmer "arduino" on port "COM5" failed
11/08/2023 13:39:34(353): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:34(353): <>c.<RunAvrDude>b__15_1(): avrdude done.  Thank you.
11/08/2023 13:39:34(353): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:34(398): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:34(398): <>c.<RunAvrDude>b__15_0(): 
11/08/2023 13:39:34(398): MobiFlightFirmwareUpdater.RunAvrDude(): Firmware upload exit code: 1.
11/08/2023 13:39:34(398): MobiFlightFirmwareUpdater.RunAvrDude(): ExitCode: 1 => Something went wrong when flashing with command 
 C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\Arduino\hardware\tools\avr\bin\avrdude -C"C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\Arduino\hardware\tools\avr\etc\avrdude.conf" -x attempts=1 -patmega328p -carduino -PCOM5 -b115200 -D -Uflash:w:"C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\firmware\mobiflight_nano_2_4_2.hex":i.
11/08/2023 13:39:34(398): MobiFlightFirmwareUpdater.RunAvrDude(): C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\Arduino\hardware\tools\avr\bin\avrdude -C"C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\Arduino\hardware\tools\avr\etc\avrdude.conf" -x attempts=1 -patmega328p -carduino -PCOM5 -b57600 -D -Uflash:w:"C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\firmware\mobiflight_nano_2_4_2.hex":i
11/08/2023 13:39:34(586): <>c.<RunAvrDude>b__15_1(): avrdude: Setting number of retry attempts to 1
11/08/2023 13:39:36(434): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:36(444): <>c.<RunAvrDude>b__15_1(): avrdude: AVR device initialized and ready to accept instructions
11/08/2023 13:39:36(455): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:36(456): <>c.<RunAvrDude>b__15_1(): Reading | ################################################## | 100% 0.00s
11/08/2023 13:39:36(458): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:36(459): <>c.<RunAvrDude>b__15_1(): avrdude: Device signature = 0x1e950f (probably m328p)
11/08/2023 13:39:36(460): <>c.<RunAvrDude>b__15_1(): avrdude: reading input file "C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\firmware\mobiflight_nano_2_4_2.hex"
11/08/2023 13:39:36(469): <>c.<RunAvrDude>b__15_1(): avrdude: writing flash (24456 bytes):
11/08/2023 13:39:36(471): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:43(39): <>c.<RunAvrDude>b__15_1(): Writing | ################################################## | 100% 6.57s
11/08/2023 13:39:43(41): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:43(42): <>c.<RunAvrDude>b__15_1(): avrdude: 24456 bytes of flash written
11/08/2023 13:39:43(43): <>c.<RunAvrDude>b__15_1(): avrdude: verifying flash memory against C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\firmware\mobiflight_nano_2_4_2.hex:
11/08/2023 13:39:43(45): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:47(732): <>c.<RunAvrDude>b__15_1(): Reading | ################################################## | 100% 4.69s
11/08/2023 13:39:47(733): <>c.<RunAvrDude>b__15_1(): avrdude: 24456 bytes of flash verified
11/08/2023 13:39:47(735): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:47(775): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:47(775): <>c.<RunAvrDude>b__15_1(): avrdude done.  Thank you.
11/08/2023 13:39:47(775): <>c.<RunAvrDude>b__15_1(): 
11/08/2023 13:39:47(775): <>c.<RunAvrDude>b__15_0(): 
11/08/2023 13:39:47(775): MobiFlightFirmwareUpdater.RunAvrDude(): Firmware upload exit code: 0.`

When the log level is set to **info**.
`11/08/2023 13:41:55(148): ExitCode: 1 => Something went wrong when flashing with command 
 C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\Arduino\hardware\tools\avr\bin\avrdude -C"C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\Arduino\hardware\tools\avr\etc\avrdude.conf" -x attempts=1 -patmega328p -carduino -PCOM5 -b115200 -D -Uflash:w:"C:\Users\simonr\source\repos\simontrhodes\MobiFlight-Connector\bin\Debug\firmware\mobiflight_nano_2_4_2.hex":i.
`
The bug is only with the logging.

**Comment by simontrhodes** [comment] 2023-11-08 13:57
Attached is the log file with logging set to Error.
[log level error.txt](https://github.com/MobiFlight/MobiFlight-Connector/files/13297435/log.level.error.txt)

**Comment by neilenns** [comment] 2023-11-08 14:01
From the logs, the first flash attempt at 115200 baud fails. The second attempt is at 57600 and works. This is the expected log output from an old bootloader nano getting flashed.

Looks like somehow the first flash error is the one getting displayed, instead of the success message for the second attempt at the slower baud rate.

**Comment by neilenns** [comment] 2023-11-08 14:02
@DocMoebiuz I'd be interested in seeing your logs, to see if the failure on the first flash is the same. In Simon's case it is this:

```
avrdude: stk500_getsync() attempt 1 of 1: not in sync: resp=0x31
```

**Comment by simontrhodes** [comment] 2023-11-08 14:02
Attached is the log file with logging set to Error.
[log level error.txt](https://github.com/MobiFlight/MobiFlight-Connector/files/13297528/log.level.error.txt)

**Comment by simontrhodes** [comment] 2023-11-08 14:05
> From the logs, the first flash attempt at 115200 baud fails. The second attempt is at 57600 and works. This is the expected log output from an old bootloader nano getting flashed.
> 
> Looks like somehow the first flash error is the one getting displayed, instead of the success message for the second attempt at the slower baud rate.

Yes, this is what seems to be happening. 
The error logging should be deferred until the whole process has finished.

**Comment by simontrhodes** [comment] 2023-11-08 14:12
This is the board I used, SunFounder Nano V4.0.
[https://www.sunfounder.com/products/arduino-nano-board](url)
It uses fake Prolific 2303 serial chip.
VID_067B PID_2303

**Comment by neilenns** [comment] 2023-11-08 16:03
That shouldn't have any impact. Log.Instance only logs to the mobiflight log system, it doesn't have anything to do with errors displayed to the user.

**Comment by neilenns** [comment] 2023-11-08 16:04
Wait, are you saying the error ONLY shows in the logs? Or does it pop up as a dialog?

If it shows in the logs then it is correct. The first attempt failed, and the log files correctly report that.

**Comment by simontrhodes** [comment] 2023-11-08 17:18
No popup error, just displayed in the log window.
The problem is the popup closes automatically.
If you miss the popup, then you only see the error in the MobiFlight log window.
Please see the attached screenshot.
![Capture](https://github.com/MobiFlight/MobiFlight-Connector/assets/24565002/14efb6c4-2b0a-4a1d-ae80-198bb7dcca41)

**Comment by neilenns** [comment] 2023-11-08 20:14
There isn't anything to do here. The dialog is correctly showing the flash completed, and the log is correctly reporting the initial flash failed.

**Comment by DocMoebiuz** [comment] 2023-11-09 08:24
Thanks! I will close it.

**Comment by DocMoebiuz** [comment] 2023-11-09 08:26
Re-opening: a success log message would be actually nice in general.

**Comment by simontrhodes** [comment] 2023-11-09 09:24
@DocMoebiuz 
In this situation only part of the process fails, which is expected behaviour.
The whole process completes successfully as the Arduino firmware is uploaded on the 2nd attempt.
I think the error message causes confusion, unless you understand how the flashing process works.
Even when it has worked the user sees an error message, which we know can be ignored but a new user doesn't.
My fix above only shows the error message if the whole flashing process fails completely.

**Comment by DocMoebiuz** [comment] 2023-11-09 09:59
> @DocMoebiuz In this situation only part of the process fails, which is expected behaviour. The whole process completes successfully as the Arduino firmware is uploaded on the 2nd attempt. I think the error message causes confusion, unless you understand how the flashing process works. Even when it has worked the user sees an error message, which we know can be ignored but a new user doesn't. My fix above only shows the error message if the whole flashing process fails completely.

i totally understand - but apparently a success log message is missing at the end. We should add one.

**Comment by simontrhodes** [comment] 2023-11-09 10:06
There is a plot twist.
This happens when log level is set to "Error".
Success is not an error.

**Comment by neilenns** [comment] 2023-11-09 12:43
> My fix above only shows the error message if the whole flashing process fails completely.

This is a log of everything that's happening, not a log of the outcome of the flashing process. Part of the flashing process *did* result in an error, the first attempt. Logging that is important so we can see what is going on.

**Comment by DocMoebiuz** [comment] 2023-11-09 17:21
Why can we not add, on top, at the very end, another log statement that logs someting like "Flashing board at COM4 successful."

**Comment by neilenns** [comment] 2023-11-09 17:32
> Why can't we add, additionally, at the very end, another log statement that logs someting like "Flashing board at COM4 successful."
> 
> Sounds like we don't have that at the moment, and I can understand the confusion that if somebody only sees the error message of the first attempt and no success message.

We definitely can, didn't say we couldn't 😀

**Comment by neilenns** [comment] 2023-11-09 18:16
> Awesome! I wish there was a volunteer who could do it.... who could that be??? 🤔

<img width="714" alt="image" src="https://github.com/MobiFlight/MobiFlight-Connector/assets/9524118/0271714d-fb01-4f30-a84e-362d500c5f59">

**Closed** 2023-11-09 22:51 UTC
Labels: bug
