### ISSUE TITLE
The use of a Config Reference which has been computed by a comparison creates an nclac error. 

### ISSUE THREAD

**Issue by JueBag** [MobiFlight/MobiFlight-Connector#719] opened 2022-02-28 11:35 UTC
When using a Config Reference which has been computed in its original (output) definition line by a comparison (zu deutsch Vergleich/Interpolation) even the direct use of the value without any calculation produces an nclac error.

Tested in OFFLINE mode using Version 9.2

Steps to reproduce:
Create an output A that gets a fixed value via transform, to be set with MobiFlight Variables selected. (Outside a test a connected FSUIPC Value could be used). 
Create a second output B that uses A as Config Reference with no transformation but with a comparison.  Also created with MobiFlight Variables selected. 
Create a third output C that use B as Config Reference with no transformation.  Also created with MobiFlight Variables selected. 
All three lines are to be activated.
Pressing the Start-Icon shows the errors:
_Problem with transform. Bei der Anwendung Ihrer Formel trat ein Fehler auf. Bitte prüfen Sie Ihre Formel._
 _checkPrecondition : Exception on NCalc evaluate_

Using a Transformation (formula like "100*Sin(A)")  on B instead of a comparison is working.

**Comment by pizman** [comment] 2022-03-01 10:20
Hi
This must be a Syntax Problem or a Typ of Value issue.
I can NOT reproduce the situation with a basic testing.

Please tell me exactly the work arround and not just the information what you did basically.....

1. So What Transform is done in Config 1  ( you just say "fixed value" )   
In my testing i hardcoded the transform to 5

2. What Compare is used in Config 2 ?
I use   IF Value=0  THEN   A+11    ELSE 2222

3. What do you do in Config 3 ?
I just show Refference "A" ( Config 2 Value) in Transform.

For me all is working fine..... So i expect you just did a issue in one of the Configs !


**@DocMoebiuz     Under investigation....  Probably no Bug or issue**

**Comment by JueBag** [comment] 2022-03-01 15:47
The issue correlates with [https://github.com/MobiFlight/MobiFlight-Connector/issues/376](https://github.com/MobiFlight/MobiFlight-Connector/issues/376)

**Comment by DocMoebiuz** [comment] 2022-03-01 18:41
Duplicate of https://github.com/MobiFlight/MobiFlight-Connector/issues/376

**Closed by DocMoebiuz** 2022-03-01 18:41 UTC
